name: ResQ
author: WeMake
markdown: kramdown
baseurl: 
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "ResQ by opencarecc"
tagline: "a digital solution that facilitates integration paths"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

