name: ResQ
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "ResQ by opencarecc"
tagline: "a digital solution that facilitates integration paths"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

# Facebook OpenGraph stuff
opengraph:
  title: "ResQ by opencarecc"
  url: "https://opencarecc.github.io/ResQ/"
  description: "a digital solution that facilitates integration paths"
  image_url: "https://opencarecc.github.io/ResQ/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "ResQ by opencarecc"
  title: "ResQ by opencarecc"
  description: "a digital solution that facilitates integration paths"
  creator: "opencarecc"
  domain: "https://opencarecc.github.io/ResQ/"
  image_url: "https://opencarecc.github.io/ResQ/assets/OC-Logo-socials.png"
